# Generated by Django 3.2.5 on 2023-01-15 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.PositiveIntegerField(choices=[(1, 'owner'), (2, 'admin'), (3, 'purchase manager'), (4, 'sales manager')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=500)),
                ('password2', models.CharField(max_length=30)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(choices=[('IND', 'India'), ('PAK', 'Pakistan'), ('BAN', 'Bangladesh'), ('CH', 'China'), ('US', 'Usa')], default='IND', max_length=3)),
                ('business_name', models.CharField(max_length=20)),
                ('is_admin', models.BooleanField(blank=True, default=False)),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='erp_management_app.roles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('passwod2', models.CharField(max_length=30)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('role', models.ManyToManyField(default=2, to='erp_management_app.Roles')),
            ],
        ),
    ]
