# Generated by Django 3.2.5 on 2023-01-15 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_management_app', '0002_auto_20230115_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
