# Generated by Django 3.2.5 on 2023-01-15 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_management_app', '0005_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='passwod2',
            new_name='password2',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='erp_management_app.roles'),
        ),
    ]
