# Generated by Django 3.2.5 on 2023-01-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_management_app', '0008_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='name',
            field=models.CharField(default='owner', max_length=30),
        ),
        migrations.AlterField(
            model_name='roles',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
