# Generated by Django 3.2.5 on 2023-01-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_management_app', '0009_auto_20230115_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
